name: twitter
scraper_module: search
twitter_search_module_config:
  num_results_per_search: 5
  search_queries_path: "${oc.env:HOME}/Documents/side_projects/social-media-data-scraping/src/scrapers/twitter/queries/search/search_queries.txt"
  tweet_params_to_extract:
    - content
    - id
    - date
    - conversationId
    - lang
    - hashtags
output_format: csv
pandas_to_csv_config:
  date_format: '%Y:%m:%d-%H:%M:%S'
  header: True
  index: False
  sep: "\t"
  

